# extract feature descriptors using pretrained model weights

expname: feature_extraction
# replace the following with your pretrained model path, img_dir and out_dir, respectively
ckpt_path: 'pretrained/caps-pretrained.pth'
extract_img_dir: 'media/vivekramayanam/STUDY/CSE/hp-test'
extract_out_dir: 'media/vivekramayanam/STUDY/CSE/relative-pose/kp-desc/'